#%RAML 0.8
title: pet-backend API
baseUri: http://localhost:8000/
version: v0.1
/users:
  post:
    description: Sign Up to the app using email, password and password confirmation or facebook_id and facebook_token.
    body:
      application/json:
        example: |
          {
            "user":
              {
                "email": "gonchu.b@gmail.com",
                "password": "admin1234",
                "password_confirmation": "admin1234"
              }
           }

          {
            "user": {
              "facebook_id": "1234",
              "facebook_token": "4567"
            }
          }
    responses:
      200:
        body:
          application/json:
              example: |
                {
                  "id": 13,
                  "created_at": "2015-09-09T00:17:08.293Z",
                  "facebook_id": null,
                  "authentication_token": "EBknxu26nKmxuzx_xxx2"
                }
      422:
        description: Will return error code 422 when fields are missing or email is already taken
        body:
          application/json:
            example: |
              { "errors":{ "email":["has already been taken"]}}
              { "errors":{ "email":["can't be blank"]}}
              { "errors":{ "facebook_id":["has already been taken"]}}
              { "errors":{ "facebook_id":["can't be blank"]}}
  /sign_in:
    post:
      description: Sign In to the app using email and password or facebook_token and facebook_id
      body:
        application/json:
          example: |
            {
              "user": {
                "email": "gonchu.b@gmail.com",
                "password": "admin1234"
              }
            }
            {
              "user": {
                "facebook_id": "1234",
                "facebook_token": "4567"
              }
            }
      responses:
        200:
          body:
            application/json:
                example: |
                  {
                    "id": 6,
                    "email": "gonchu.b@gmail.com",
                    "created_at": "2015-09-08T01:45:42.216Z",
                    "updated_at": "2015-09-09T00:31:34.644Z",
                    "facebook_id": null,
                    "facebook_token": null,
                    "authentication_token": "K62wJZYwP7KNMUBAQMp9"
                   }
        422:
          description: Will return error code 422 when credentials are invalid
          body:
            application/json:
              example: |
                { "error": "Invalid email or password." }
                { "error": "Invalid id or token" }
/pets:
  post:
    description: Create pet and (optionally) publish it in the app
    body:
      application/json:
        example: |
          {
            "pet": {
              "type": "Cat",
              "name": "John",
              "description": "Very nice cat.",
              "published": true,
              "gender": "male"
            }
          }

          {
            "pet": {
              "type": "Dog",
              "name": "Steve",
              "gender": "female",
              "description": "Very nice dog.",
              "published": true,
              location: "127.1,-12.0",
              "colors": "gray white",
              "metadata": "handsome"
            }
          }
    responses:
      201:
        body:
          application/json:
              example: |
                {
                  "id": 6,
                  "type": "Cat",
                  "name": "John",
                  "description": "Very nice cat.",
                  "published":false,
                  "needs_transit_home":false,
                  "created_at": "2015-09-15T03:02:16.890Z",
                  "updated_at": "2015-09-15T03:02:16.890Z"
                }
  get:
    description: Search for pets (only shows published pets)
    queryParameters:
      limit:
        displayName: limit
        type: number
        description: The max amount of pets you want in your response.
        example: 5
        required: false
      type:
        displayName: pet type
        type: string
        description: The type of pet.
        example: "Cat"
        required: false
      needs_transit_home:
        displayName: transit home
        type: boolean
        description: Whether the pets need transit home or not.
        example: true
        required: false
      vaccinated:
        displayName: vaccinated
        type: boolean
        description: Search by vaccination status.
        example: true
        required: false
      user_id:
        displayName: user id
        type: number
        description: The id of the user whose pets you want to search for.
        example: true
        required: false
      gender:
        displayName: gender
        type: string
        description: The gender of the pets to be returned (male or female).
        example: "male"
        required: false
      colors:
        displayName: colors
        type: string
        description: The colors that pets should have (they should have all of them).
        example: "black white"
        required: false
      metadata:
        displayName: metadata
        type: string
        description: Metadata to search pets. If it matches any of the metadata words, the pet is returned.
        example: "gato macho"
        required: false
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 6,
                "type": "Cat",
                "name": "John",
                "description": "Very nice cat.",
                "published": false,
                "needs_transit_home": false,
                "created_at": "2015-09-15T03:02:16.890Z",
                "updated_at": "2015-09-15T03:02:16.890Z"
              }
  /{id}:
    get:
      description: Get the pet specified by the id.
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id":11,
                  "type":"Cat",
                  "name":"John",
                  "description":"hlo",
                  "published":true,
                  "vaccinated":true,
                  "needs_transit_home":false,
                  "created_at":"2015-09-15T04:21:52.311Z",
                  "updated_at":"2015-09-23T00:17:52.432Z",
                  "user_id":1,
                  "location":"127,2",
                  "metadata":"gato macho black gray handsome",
                  "colors":"black gray",
                  "gender":"male"
                }
        404:
          description: Will return a 404 status if the pet is not found.
    put:
      description: Update the pet specified by the id.
      body:
        application/json:
          example: |
            {
              "pet": {
                "vaccinaated": false
              }
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id":11,
                  "type":"Cat",
                  "name":"John",
                  "description":"hlo",
                  "published":true,
                  "vaccinated":true,
                  "needs_transit_home":false,
                  "created_at":"2015-09-15T04:21:52.311Z",
                  "updated_at":"2015-09-23T00:17:52.432Z",
                  "user_id":1,
                  "location":"127,2",
                  "metadata":"gato macho black gray handsome",
                  "colors":"black gray",
                  "gender":"male"
                }
        404:
          description: Will return a 404 status if the pet is not found.
    delete:
      description: Delete the pet specified by the id.
      responses:
        204:
          description: Will return a 204 with no content.
        404:
          description: Will return a 404 status if the pet is not found.
    /photo:
      post:
        description: Add a photo to the given pet.
        body:
          application/file:
            example: Upload the image in a param named "image"
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "id":6,
                    "original_url":"http://localhost:8000/system/pet_images/images/000/000/006/original/imagereq.png?1443043475",
                    "medium_url":"http://localhost:8000/system/pet_images/images/000/000/006/medium/imagereq.png?1443043475",
                    "thumb_url":"http://localhost:8000/system/pet_images/images/000/000/006/thumb/imagereq.png?1443043475"
                  }
          404:
            description: Will return a 404 status if the pet is not found.
  /top:
    get:
      description: Get top 5 pets.
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "id":11,
                    "type":"Cat",
                    "gender":"male",
                    "name":"John",
                    "description":"hlo",
                    "published":true,
                    "needs_transit_home":false,
                    "created_at":"2015-09-15T04:21:52.311Z",
                    "updated_at":"2015-09-20T19:16:19.167Z",
                    "user_id":1,
                    "location":"127,2",
                    "url":"http://localhost:8000/pets/11.json"
                   },
                   {
                    "id":8,
                    "type":"Cat",
                    "gender":"male",
                    "name":"John",
                    "description":"Very nice cat.",
                    "published":true,
                    "needs_transit_home":false,
                    "created_at":"2015-09-15T03:26:02.572Z",
                    "updated_at":"2015-09-15T03:35:07.761Z",
                    "user_id":1,
                    "location":"12,-12.0",
                    "url":"http://localhost:8000/pets/8.json"
                   }
                ]
